const {mkTmp,safeRm}=require('./_tmp');
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),cp=require('node:child_process');
const {intakeEvent}=require('../scripts/intake_from_event');
const {buildSite}=require('../scripts/build_site');
const {exportPublic,scan}=require('../scripts/export_public');
const root=path.resolve(__dirname,'..'),good=fs.readFileSync(path.join(__dirname,'fixtures/intake/good-form.md'),'utf8');
const tmp=()=>mkTmp('open-door-test-');
function copy(){const dir=tmp();require('./_fixture').seed(dir);for(const rel of require('./_fixture').publicTracked(root,git(root,'ls-files','-z').split('\0').filter(Boolean)).filter(rel=>! /^(members|rooms|materials|swaps|letters|footprints)\//.test(rel))){const dest=path.join(dir,rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,rel),dest);}return dir;}
const event=(body=good,login='River')=>({action:'created',sender:{login},discussion:{user:{login,id:101},category:{slug:'check-in'},body}});
const read=(dir,rel)=>JSON.parse(fs.readFileSync(path.join(dir,rel),'utf8'));
function git(dir,...args){const r=cp.spawnSync('git',['-C',dir,...args],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();}
test('event normal check-in preserves explicit human marking',()=>{const dir=copy(),r=intakeEvent(event(),dir);assert.equal(r.ok,true);assert.deepEqual(r.warnings,[]);assert.equal(read(dir,'members/river.json').github,'river');assert.equal(read(dir,'materials/river/item-1.json').made_by,'human');});
test('gradient rejected, member received',()=>{const dir=copy(),r=intakeEvent(event(good.replace('<title>','<defs><linearGradient id="g"/></defs><title>')),dir);assert.equal(r.ok,true);assert.ok(r.warnings.some(w=>w.includes('linearGradient')));assert.ok(fs.existsSync(path.join(dir,'members/river.json')));assert.equal(fs.existsSync(path.join(dir,'materials/river')),false);});
test('non check-in is ignored and account characters normalized',()=>{const dir=copy(),e=event();e.discussion.category.slug='chat';assert.equal(intakeEvent(e,dir).skipped,true);assert.equal(fs.existsSync(path.join(dir,'members/river.json')),false);assert.equal(intakeEvent(event(good,'-River_Test-'),dir).slug,'river-test');});
test('same author editing adds material to same branch, explicit non AI',()=>{const dir=copy(),first=event(good.replace(/```svg[\s\S]*?```/,''));assert.equal(intakeEvent(first,dir).ok,true);const e=event(good+'\n### 這件素材是 AI 做的，或有 AI 參與嗎？\n否\n');e.action='edited';const r=intakeEvent(e,dir);assert.equal(r.branch,'intake/river');assert.deepEqual(r.warnings,[]);assert.equal(read(dir,'materials/river/item-1.json').made_by,'human');});
test('other author cannot change member; invalid member writes nothing',()=>{const dir=copy();intakeEvent(event(),dir);const before=fs.readFileSync(path.join(dir,'members/river.json'),'utf8');const e=event();e.sender.login='Other';assert.equal(intakeEvent(e,dir).ok,false);assert.equal(fs.readFileSync(path.join(dir,'members/river.json'),'utf8'),before);const spoof=event(good,'example-person');assert.equal(intakeEvent(spoof,dir).ok,false);const bad=event(good.replace('- [X] 主人','- [ ] 主人'),'Missing');assert.equal(intakeEvent(bad,dir).ok,false);assert.equal(fs.existsSync(path.join(dir,'members/missing.json')),false);});
test('build excludes unconsented and draft members, rooms and material references',()=>{const dir=copy();const file=path.join(dir,'members/example-person.json'),m=read(dir,'members/example-person.json');m.owner_consent=false;fs.writeFileSync(file,JSON.stringify(m));const out=path.join(dir,'_site'),r=buildSite(dir,out);assert.deepEqual(r.members.map(m=>m.id),['aiwff-main-brain','example-company']);assert.equal(r.rooms['example-person'],undefined);assert.ok(r.catalog.every(c=>c.owner==='example-company'));assert.equal(fs.existsSync(path.join(out,'materials/example-person')),false);assert.equal(fs.existsSync(path.join(out,'docs')),false);assert.equal(read(out,'site/members.json').length,2);});
test('export tracked files excludes drafts and private documents; gate detects internal marker with line number',()=>{const dir=copy();fs.mkdirSync(path.join(dir,'scripts'),{recursive:true});fs.copyFileSync(path.join(root,'scripts/export_public.js'),path.join(dir,'scripts/export_public.js'));git(dir,'init');git(dir,'add','.');const out=path.join(tmp(),'snapshot');const r=exportPublic(out,dir);assert.equal(fs.existsSync(path.join(out,'members/aiwff-main-brain.json')),true);assert.equal(fs.existsSync(path.join(out,'rooms/aiwff-main-brain')),true);fs.writeFileSync(path.join(dir,'README.md'),'未來村\n'+'INTERNAL'+'_MARK\n');git(dir,'add','README.md');const fail=exportPublic(path.join(tmp(),'snapshot'),dir);assert.equal(fail.ok,false);assert.equal(fs.existsSync(fail.out),false);assert.ok(fail.hits.some(h=>h.startsWith('README.md:2 ')));assert.ok(fail.control>=1);const cli=cp.spawnSync(process.execPath,[path.join(dir,'scripts/export_public.js'),path.join(tmp(),'snapshot')],{encoding:'utf8'});assert.equal(cli.status,1);});
test('public gate detects local path and private mailbox',()=>{const dir=tmp();fs.writeFileSync(path.join(dir,'sample.txt'),'C:'+String.fromCharCode(92)+'private\n'+'test@gm'+'ail.com');assert.equal(scan(dir,['sample.txt']).hits.length,2);});
test('independent member branches merge without generated-file conflict and build both',()=>{const dir=copy();git(dir,'init');git(dir,'add','.');const commit=msg=>git(dir,'-c','user.name=zaxardery8011-design','-c','user.email=283511868+zaxardery8011-design@users.noreply.github.com','commit','-m',msg);commit('Fixture baseline');const base=git(dir,'rev-parse','HEAD');git(dir,'switch','-c','fixture-a');intakeEvent(event(good,'Alice'),dir);git(dir,'add','members','rooms','materials');commit('Member A');git(dir,'switch','-c','fixture-b',base);intakeEvent(event(good,'Bob'),dir);git(dir,'add','members','rooms','materials');commit('Member B');git(dir,'switch','-c','fixture-merge',base);for(const b of ['fixture-a','fixture-b'])git(dir,'-c','user.name=zaxardery8011-design','-c','user.email=283511868+zaxardery8011-design@users.noreply.github.com','merge','-m','Merge fixture',b);const result=buildSite(dir);assert.ok(result.members.some(m=>m.id==='alice'));assert.ok(result.members.some(m=>m.id==='bob'));});

test('export excludes unconsented member and its room and materials',()=>{const dir=copy(),m=read(dir,'members/example-person.json');m.owner_consent=false;fs.writeFileSync(path.join(dir,'members/example-person.json'),JSON.stringify(m));git(dir,'init');git(dir,'add','.');const out=path.join(tmp(),'snapshot');exportPublic(out,dir);for(const rel of ['members/example-person.json','rooms/example-person','materials/example-person'])assert.equal(fs.existsSync(path.join(out,rel)),false);});
