const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const {mkTmp}=require('./_tmp'),{gate}=require('../scripts/intake_gate'),{checkMember,safeSvg,materialSvgIssues,SLUG}=require('../scripts/check_members'),{intakeEvent}=require('../scripts/intake_from_event'),{exportPublic}=require('../scripts/export_public'),{buildSite}=require('../scripts/build_site');
const root=path.resolve(__dirname,'..'),good=fs.readFileSync(path.join(__dirname,'fixtures/intake/good-form.md'),'utf8');
test('workflow defense configuration: pinned actions, credentials, concurrency and pre-upload checks',()=>{const read=name=>fs.readFileSync(path.join(root,'.github/workflows',name),'utf8'),intake=read('intake.yml'),pages=read('pages.yml'),letters=read('letters.yml');for(const name of fs.readdirSync(path.join(root,'.github/workflows')))for(const match of read(name).matchAll(/uses: actions\/[^@\s]+@([^\s]+)/g))assert.match(match[1],/^[a-f0-9]{40}$/);assert.ok(intake.includes('cron: "*/15 * * * *"'));assert.ok(intake.includes('cancel-in-progress: false'));assert.ok(intake.includes('group: intake-global'));assert.ok(intake.includes('node scripts/intake_sweep.js'));assert.ok(fs.readFileSync(path.join(root,'scripts/intake_sweep.js'),'utf8').includes("'users/'+login"));for(const name of ['check.yml','pages.yml'])assert.ok(read(name).includes('persist-credentials: false'));const upload=pages.indexOf('uses: actions/upload-pages-artifact');for(const command of ['node scripts/check_members.js','node --test'])assert.ok(pages.indexOf(command)>=0&&pages.indexOf(command)<upload);const deliver=letters.split('  deliver:')[1].split('    runs-on:')[0];assert.ok(deliver.includes('contents: write'));assert.ok(!deliver.includes('pages:')&&!deliver.includes('id-token:'));});
const event=body=>({action:'created',sender:{login:'River'},discussion:{user:{login:'River',id:101},category:{slug:'check-in'},body}});
function copy(){const dir=mkTmp('security-'),p=cp.spawnSync('git',['-C',root,'ls-files','-z'],{encoding:'utf8'});assert.equal(p.status,0);require('./_fixture').seed(dir);for(const rel of require('./_fixture').publicTracked(root,p.stdout.split('\0').filter(Boolean)).filter(rel=>! /^(members|rooms|materials|swaps|letters|footprints)\//.test(rel))){const dest=path.join(dir,rel);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,rel),dest);}return dir;}
test('age and queue boundaries; existing intake can update while queue is full',()=>{const now=Date.parse('2026-10-08T00:00:00Z'),user={created_at:'2026-10-01T00:00:00Z'},prs=n=>Array.from({length:n},(_,i)=>({headRefName:'intake/p-'+i}));assert.equal(gate(user,prs(50),event(good),now).ok,true);assert.equal(gate(user,prs(51),event(good),now).ok,false);assert.equal(gate(user,[...prs(51),{headRefName:'intake/river'}],event(good),now).ok,true);for(const created_at of ['invalid','2026-10-02T00:00:00Z','2026-10-09T00:00:00Z'])assert.equal(gate({created_at},[],event(good),now).ok,false);});
test('private kinds fail intake without echoing values or writing; scans unmapped fields',()=>{for(const value of ['0912-000-000','02-2000-0000','test@example.invalid','A100000000','範例市範例區範例路一號']){const dir=mkTmp('security-'),r=intakeEvent(event(good+'\n### 未知欄位\n'+value),dir);assert.equal(r.ok,false,value);assert.ok(r.kinds.length);assert.ok(!JSON.stringify(r).includes(value));assert.equal(fs.existsSync(path.join(dir,'members')),false);}});
test('explicit contact consent permits phones and email only; other fields and identity remain fatal',()=>{const m={type:'person',handle:'test',intro:'hello',avatar:1,owner_consent:true};for(const contact of ['0912-000-000','test@example.invalid']){assert.ok(!checkMember({...m,card:{contact,public_ok:true}}).some(i=>i.fatal));assert.ok(checkMember({...m,card:{contact,public_ok:false}}).some(i=>i.fatal));const dir=mkTmp('security-');assert.equal(intakeEvent(event(good+'\n### 名片\n'+JSON.stringify({contact,public_ok:true})),dir).ok,true);}assert.ok(checkMember({...m,card:{contact:'A100000000',public_ok:true}}).some(i=>i.fatal));assert.ok(checkMember({...m,intro:'test@example.invalid',card:{contact:'test@example.invalid',public_ok:true}}).some(i=>i.fatal));assert.ok(checkMember({...m,intro:'00000000'}).some(i=>i.kind==='統一編號'&&!i.fatal));});
test('both SVG paths reject style, unknown elements and encoded CSS references',()=>{for(const svg of ['<svg><rect style="fill:red"/></svg>','<svg><rect style="fill:&#117;rl(x)"/></svg>','<svg><style>@import x</style></svg>','<svg><foreignObject/></svg>']){assert.equal(safeSvg(svg),false);assert.ok(materialSvgIssues(svg).length);}assert.equal(safeSvg('<svg><rect width="1"/></svg>'),true);});
test('reserved device slugs rejected at checker and intake',()=>{for(const slug of ['con','aux','nul','prn',...Array.from({length:9},(_,i)=>'com'+(i+1)),...Array.from({length:9},(_,i)=>'lpt'+(i+1))]){assert.equal(SLUG.test(slug),false);const e=event(good);e.sender.login=e.discussion.user.login=slug;assert.equal(intakeEvent(e,mkTmp('security-')).ok,false);}assert.equal(SLUG.test('company'),true);});
test('full tracked-tree export includes captain and null byte rejects entire batch',()=>{const dir=copy();let p=cp.spawnSync('git',['-C',dir,'init']);assert.equal(p.status,0);p=cp.spawnSync('git',['-C',dir,'add','.']);assert.equal(p.status,0);const out=path.join(mkTmp('security-'),'snapshot'),r=exportPublic(out,dir);assert.equal(r.ok,true);assert.ok(r.control>=1);assert.ok(fs.existsSync(path.join(out,'members/aiwff-main-brain.json')));assert.ok(r.files.includes('CONTRIBUTING.md'));fs.writeFileSync(path.join(dir,'bad.bin'),Buffer.from([65,0,66]));assert.equal(cp.spawnSync('git',['-C',dir,'add','bad.bin']).status,0);const fail=exportPublic(path.join(mkTmp('security-'),'snapshot'),dir);assert.equal(fail.ok,false);assert.ok(fail.hits.some(h=>h.includes('null byte')));assert.equal(fs.existsSync(fail.out),false);});
test('build omits unapproved contact from JSON, source machine layer and embedded data; CSP uses external scripts',()=>{const dir=copy(),file=path.join(dir,'members/example-person.json'),m=JSON.parse(fs.readFileSync(file));m.card={contact:'private-contact',public_ok:false};m.company={card:{contact:'private-company-contact',public_ok:false}};fs.writeFileSync(file,JSON.stringify(m));const out=path.join(mkTmp('security-'),'site');buildSite(dir,out);for(const rel of ['site/members.json','members/example-person.json','site/index.html'])assert.ok(!fs.readFileSync(path.join(out,rel),'utf8').includes('private-contact'));const html=fs.readFileSync(path.join(out,'site/index.html'),'utf8');assert.ok(html.includes("script-src 'self'"));assert.ok(html.includes('<script src="app.js"></script>'));assert.ok(!/<script>/.test(html));assert.ok(fs.readFileSync(path.join(out,'site/app.js'),'utf8').includes("'@'+m.github"));});
